### PR TITLE
composer.json

### PR DESCRIPTION
**Pull request by nhp**
Adding composer.json for installation. First composer.json for a project so please check it if everything is done correctly. Working at least for me from my fork so it should not be that bad.

### CODE REVIEW

**Comment by SchumacherFM** [comment]
Is that project dead?

**Comment by sprankhub** [comment]
@SchumacherFM Hopefully not... @IvanChepurnyi

**Comment by IvanChepurnyi** [comment]
This is not going to be continued in current code base. It will be fully rewritten to realise different rewrite mechanism, that will be much more faster and more efficient.

**Comment by sprankhub** [comment]
Sounds great,  thank you! Did you already start or have any ETA?

**Comment by Flyingmana** [comment]
that is not a good reason to not merge this,
and waiting over 2 years for a rewritten extension is not a good excuse.

**Comment by sylvainraye** [comment]
@Flyingmana +1

**Comment by Flyingmana** [comment]
I Forket the project now, added this PR, added the Fork to packages.firegento.com and also added travisCI.

https://github.com/Cotya/EcomDev_UrlRewrite

**Pull request closed without merging**
